### ISSUE TITLE
You sure that's legal where you live?...

### ISSUE THREAD

**Issue by needPizza** [rdlauer/pispeedtrap#1]
It's all cool, but unless you live somewhere where collecting people's data without their consent is something you can do without being a law enforcement agent, not only is it useless, as you couldn't use it as a proof in a court, but you yourself would be liable if you were to actually deploy it anywhere where the camera sees something that isn't your property. Just saying, man.

**Comment by rdlauer** [comment]
It's a good point, but if you read the tutorial there is no PI gathered whatsoever. The ML model is literally just identifying the type of vehicle and nothing more.
