### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by andrewm659** [rdlauer/pispeedtrap#2]
Can you upload a keys.py file?  Without all of your information in it?  It seems like there is missing bit of information to get this up and running.  Should there be a hidden file to put api keys?

We have talked on reddit but I assume this is a better way to reach out.  I would like to get this running for my neighborhood.  Including modifying the code to not use cell card, but just using wireless.

This is an awesome project!

Thanks again!

**Comment by rdlauer** [comment]
You actually don't need the `keys.py` file. On line 27 just insert your Notehub productUID:

https://github.com/rdlauer/pispeedtrap/blob/main/main.py#L27

```
productUID = "your-product-uid"
```
